// <auto-generated />
using System;
using GuangYuan.GY001.TemplateDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuangYuan.GY001.TemplateDb.Migrations
{
    [DbContext(typeof(GY02TemplateContext))]
    [Migration("20221121085411_22112101")]
    partial class _22112101
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GuangYuan.TemplateDb.GameThingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("GId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GenusString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonObjectString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThingTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
