// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OW.Game.Store;

#nullable disable

namespace UserDb.Migrations
{
    [DbContext(typeof(GY02UserContext))]
    [Migration("20231120090817_23112001")]
    partial class _23112001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OW.Game.Store.Base.GameRedeemCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(0)
                        .HasComment("兑换码，也是Id。");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Code");

                    b.ToTable("GameRedeemCode");
                });

            modelBuilder.Entity("OW.Game.Store.GameShoppingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("BinaryArray")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Confirm1")
                        .HasColumnType("bit");

                    b.Property<bool>("Confirm2")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonObjectString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShoppingOrder");
                });

            modelBuilder.Entity("OW.Game.Store.GameShoppingOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("BinaryArray")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Count")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("GameShoppingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GoodsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameShoppingOrderId");

                    b.ToTable("GameShoppingOrderDetail");
                });

            modelBuilder.Entity("OW.Game.Store.OrphanedThing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("BinaryArray")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("ExtraDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExtraGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtraString")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("JsonObjectString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ExtraGuid", "ExtraDecimal", "ExtraString");

                    b.HasIndex("ExtraGuid", "ExtraString", "ExtraDecimal");

                    b.ToTable("OrphanedThings");
                });

            modelBuilder.Entity("OW.Game.Store.ServerConfigItem", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastModifyUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("ServerConfig");
                });

            modelBuilder.Entity("OW.Game.Store.VirtualThing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("BinaryArray")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("ExtraDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExtraGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtraString")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("JsonObjectString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ExtraGuid", "ExtraDecimal", "ExtraString");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExtraGuid", "ExtraDecimal", "ExtraString"), new[] { "ParentId" });

                    b.HasIndex("ExtraGuid", "ExtraString", "ExtraDecimal");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ExtraGuid", "ExtraString", "ExtraDecimal"), new[] { "ParentId" });

                    b.ToTable("VirtualThings");
                });

            modelBuilder.Entity("OW.Game.Store.GameShoppingOrderDetail", b =>
                {
                    b.HasOne("OW.Game.Store.GameShoppingOrder", null)
                        .WithMany("Detailes")
                        .HasForeignKey("GameShoppingOrderId");
                });

            modelBuilder.Entity("OW.Game.Store.VirtualThing", b =>
                {
                    b.HasOne("OW.Game.Store.VirtualThing", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OW.Game.Store.GameShoppingOrder", b =>
                {
                    b.Navigation("Detailes");
                });

            modelBuilder.Entity("OW.Game.Store.VirtualThing", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
