// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OW.GameDb;

#nullable disable

namespace LoggingDb.Migrations
{
    [DbContext(typeof(GY02LogginContext))]
    [Migration("20240220042550_24022001")]
    partial class _24022001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OW.GameDb.ActionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("ActionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("行为Id。如Logined , ShoppingBuy.xxxxxxxxxxxxxxxxxxxx==。");

                    b.Property<decimal>("ExtraDecimal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("额外数字，具体意义取决于该条记录的类型。");

                    b.Property<Guid?>("ExtraGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("额外Guid。");

                    b.Property<string>("ExtraString")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("额外的字符串，通常行为Id，最长64字符。");

                    b.Property<string>("JsonObjectString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("WorldDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("这个行为发生的世界时间。");

                    b.HasKey("Id");

                    b.HasIndex("ActionId", "WorldDateTime");

                    b.HasIndex("WorldDateTime", "ActionId");

                    b.ToTable("ActionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
